# Generated by Django 5.2.6 on 2025-10-01 05:39

import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude in decimal degrees (e.g., -90.000000 to 90.000000)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude in decimal degrees (e.g., -180.000000 to 180.000000)', max_digits=9, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Score')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['name'],
            },
        ),
    ]
