# Generated by Django 5.2.6 on 2025-10-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
