# Generated by Django 5.2.6 on 2025-10-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_place_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude in decimal degrees (e.g., -180.000000 to 180.000000)', max_digits=10, null=True),
        ),
    ]
