# Generated by Django 5.2.6 on 2025-10-10 07:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_category_place_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('food', 'Food Quality'), ('coffee', 'Coffee Quality'), ('drinks', 'Drinks Quality'), ('menu_variety', 'Menu Variety'), ('service', 'Service'), ('ambiance', 'Ambiance & Atmosphere'), ('value', 'Value for Money'), ('cleanliness', 'Cleanliness Quality'), ('location', 'Location & Accessibility'), ('parking', 'Parking Availability'), ('facility', 'Comfort & Facilities Quality'), ('family_friendly', 'Family Friendliness'), ('groups', 'Suitability for Groups'), ('work', 'Suitability for Working/Studying')], max_length=35, verbose_name='Item Type')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Order')),
                ('is_applicable', models.BooleanField(default=True, help_text='Uncheck this if the item is not applicable for this review (e.g., no coffee).', verbose_name='Is Applicable')),
                ('score', models.IntegerField(help_text='One means at least and 5 menas the most', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Score')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.review', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Review Item',
                'verbose_name_plural': 'Review Items',
                'ordering': ('order',),
                'unique_together': {('review', 'item_type')},
            },
        ),
    ]
