# Generated by Django 5.2.6 on 2025-10-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_review_reviewitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewitem',
            name='score',
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
