# Generated by Django 5.2.6 on 2025-10-10 07:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_reviewitem_score_reviewitem_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='restaurants.review', verbose_name='Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'review')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_applicable', models.BooleanField(default=True, help_text='Uncheck this if the item is not applicable for this review (e.g., no coffee)', verbose_name='Is Applicable')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Score')),
                ('extra_notes', models.TextField(blank=True, help_text='If the item needs any extra details, mention them as short as possible', verbose_name='Extra notes')),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='restaurants.reviewitem', verbose_name='Review Item')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='restaurants.vote', verbose_name='Vote')),
            ],
        ),
    ]
