# Generated by Django 5.2.6 on 2025-10-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_vote_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='VoteResponse',
        ),
    ]
