# Generated by Django 5.2.6 on 2025-10-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_rename_response_voteresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteresponse',
            options={'ordering': ('review_item__order',), 'verbose_name': 'Vote Response', 'verbose_name_plural': 'Vote Responses'},
        ),
    ]
