# Generated by Django 5.2.6 on 2025-10-10 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_voteresponse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
