# Generated by Django 5.2.6 on 2025-10-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_vote_created_vote_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteresponse',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='voteresponse',
            name='review_item',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='VoteResponse',
        ),
    ]
