# Generated by Django 5.2.6 on 2025-10-10 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_vote_voteresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceVoteSummary',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('total_votes', models.PositiveIntegerField(default=0, verbose_name='Total Votes')),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Score')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_summaries', to='restaurants.place', verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Place Vote Summary',
                'verbose_name_plural': 'Place Vote Summaries',
            },
        ),
    ]
