# Generated by Django 5.2.6 on 2025-10-10 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_placevotesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceReviewItemSummary',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_type', models.CharField(choices=[('food', 'Food Quality'), ('coffee', 'Coffee Quality'), ('drinks', 'Drinks Quality'), ('menu_variety', 'Menu Variety'), ('service', 'Service'), ('ambiance', 'Ambiance & Atmosphere'), ('value', 'Value for Money'), ('cleanliness', 'Cleanliness Quality'), ('location', 'Location & Accessibility'), ('parking', 'Parking Availability'), ('facility', 'Comfort & Facilities Quality'), ('family_friendly', 'Family Friendliness'), ('groups', 'Suitability for Groups'), ('work', 'Suitability for Working/Studying')], max_length=35, verbose_name='Item Type')),
                ('total_votes', models.PositiveIntegerField(default=0, verbose_name='Total Applicable Votes')),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Average Score')),
                ('concatenated_notes', models.TextField(blank=True, help_text='A compilation of all extra notes provided for this item.', verbose_name='All Notes')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_summaries', to='restaurants.place', verbose_name='Place')),
                ('vote_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_summaries', to='restaurants.placevotesummary', verbose_name='Vote Summary')),
            ],
            options={
                'verbose_name': 'Place Review Item Summary',
                'verbose_name_plural': 'Place Review Item Summaries',
                'ordering': ['place', 'item_type'],
                'unique_together': {('place', 'item_type')},
            },
        ),
    ]
