# Generated by Django 5.2.6 on 2025-10-10 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_placereviewitemsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placevotesummary',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_summaries', to='restaurants.place', verbose_name='Place'),
        ),
    ]
