# Generated by Django 5.2.6 on 2025-10-11 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_alter_placevotesummary_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteresponse',
            name='review_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='restaurants.reviewitem', verbose_name='Review Item'),
        ),
    ]
