# Generated by Django 5.2.6 on 2025-10-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_voteresponse_review_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='editable',
            field=models.BooleanField(default=False, verbose_name='Editable'),
        ),
    ]
