# Generated by Django 5.2.6 on 2025-10-11 07:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_vote_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteresponse',
            name='review_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='restaurants.reviewitem', verbose_name='Review Item'),
        ),
        migrations.AlterField(
            model_name='voteresponse',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Score'),
        ),
    ]
