# Generated by Django 4.2.1 on 2024-01-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
