# Generated by Django 5.0.1 on 2024-04-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
