# Generated by Django 5.0.1 on 2024-04-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_is_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='website_header',
            field=models.CharField(default='', max_length=200),
        ),
    ]
