# Generated by Django 5.0.1 on 2024-04-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_website_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
