# Generated by Django 5.0.1 on 2024-04-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='website_header',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
