# Generated by Django 4.1.5 on 2023-01-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='require',
            field=models.CharField(default='message', max_length=14),
        ),
    ]
