# Generated by Django 5.0.4 on 2024-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_require'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
