# Generated by Django 6.0 on 2025-12-10 07:14

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for row in Project.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, blank=True,),
        ),
        
        migrations.RunPython(gen_uuid),
        
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    
    ]
