# Generated by Django 6.0 on 2025-12-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_role_colleague_colleaguetranslation_roletranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='colleagues',
            field=models.ManyToManyField(to='projects.colleague', verbose_name='Colleagues'),
        ),
    ]
