# Generated by Django 6.0 on 2025-12-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_stack_project_stacks_stacktranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='colleagues',
            field=models.ManyToManyField(blank=True, to='projects.colleague', verbose_name='Colleagues'),
        ),
    ]
