# Generated by Django 6.0 on 2025-12-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_colleagues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('rank',)},
        ),
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Rank'),
        ),
    ]
