# Generated by Django 5.0.4 on 2024-10-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='georecord',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
