# Generated by Django 5.0.4 on 2024-10-15 07:42

from django.db import migrations, models

def set_updated_field(apps, schema_editor):
    GeoRecord = apps.get_model('generals', 'GeoRecord')
    for obj in GeoRecord.objects.all():
        obj.updated = obj.created
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0002_georecord_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='georecord',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, blank=True),
        ),
        migrations.RunPython(set_updated_field),
        
        migrations.AlterField(
            model_name='georecord',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
