# Generated by Django 4.1.4 on 2022-12-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
