# Generated by Django 5.2.5 on 2025-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_access',
            field=models.BooleanField(default=False),
        ),
    ]
