# Generated by Django 5.2.5 on 2025-08-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_ai_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accounting_access',
            field=models.BooleanField(default=False),
        ),
    ]
