# Generated by Django 5.2.5 on 2025-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_accounting_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_access',
            field=models.BooleanField(default=False),
        ),
    ]
