# Generated by Django 5.0.4 on 2024-11-14 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('PDF', 'PDF'), ('DOCS', 'DOCS'), ('image', 'Image'), ('link', 'Link'), ('video_file', 'Video file'), ('script', 'Script')], default='PDF', max_length=15)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/lessons/', verbose_name='File')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('script', models.TextField(blank=True, null=True, verbose_name='Script')),
                ('rank', models.PositiveSmallIntegerField(default=1, verbose_name='Rank')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.post', verbose_name='Post')),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
    ]
