# Generated by Django 5.0.4 on 2024-11-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('code', 'Code'), ('PDF', 'PDF'), ('DOCS', 'DOCS'), ('image', 'Image'), ('link', 'Link'), ('video_file', 'Video file'), ('script', 'Script')], default='PDF', max_length=15),
        ),
    ]
