# Generated by Django 4.1.5 on 2023-01-12 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.CharField(max_length=350)),
                ('correct', models.CharField(max_length=350, verbose_name='Correct answer')),
                ('wrong_1', models.CharField(max_length=350, verbose_name='Wrong answer 1')),
                ('wrong_2', models.CharField(max_length=350, verbose_name='Wrong answer 2')),
                ('wrong_3', models.CharField(max_length=350, verbose_name='Wrong answer 3')),
                ('link', models.URLField(blank=True, null=True)),
                ('difficulty', models.IntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('correct_responses', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('difficulty', models.CharField(choices=[(1, 'Easy 1-3-1'), (2, 'Medium 1-2-2'), (3, 'Hard 1-1-3')], default=1, max_length=50)),
                ('number_of_questions', models.IntegerField(default=5)),
                ('questions', models.ManyToManyField(related_name='quizes', to='quizes.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
