# Generated by Django 4.1.5 on 2023-01-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_quiz_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Easy 1-3-1'), ('2', 'Medium 1-2-2'), ('3', 'Hard 1-1-3')], default='1', max_length=50),
        ),
    ]
