# Generated by Django 4.1.5 on 2023-01-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(),
        ),
    ]
