# Generated by Django 4.1.5 on 2023-01-18 06:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_quizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
