# Generated by Django 4.1.5 on 2023-01-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0008_quiz_final_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='step',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
