# Generated by Django 4.1.5 on 2023-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0011_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
