# Generated by Django 4.1.5 on 2023-01-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0012_quizresponse_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '1'), (2, '1'), (3, '1'), (4, '1'), (5, '1')], default=1),
        ),
    ]
