# Generated by Django 4.1.5 on 2023-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0013_alter_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
