# Generated by Django 4.1.7 on 2023-02-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0017_compliment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliment',
            name='difficulty',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
