# Generated by Django 5.2.4 on 2025-07-27 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=120)),
                ('chat_id', models.CharField(max_length=100, verbose_name='')),
                ('input_token', models.IntegerField(verbose_name='Input token')),
                ('output_token', models.IntegerField(verbose_name='Output token')),
                ('total_token', models.IntegerField(verbose_name='Total token')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', verbose_name='Role')),
                ('content', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
