# Generated by Django 5.2.4 on 2025-08-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_chat_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ai/prompts/'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(choices=[('', 'Not Applied'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('doc', 'Document')], default='', max_length=12),
        ),
    ]
