# Generated by Django 5.2.5 on 2025-08-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_message_file_message_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('label', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
