# Generated by Django 5.2.5 on 2025-08-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_chatmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
