# Generated by Django 5.2.5 on 2025-08-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_chatmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='output_token',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
