# Generated by Django 5.2.5 on 2025-08-16 05:48

from django.db import migrations, models

def update_usage_count(apps, schema_editor):
    # Get the ChatModel model from the apps registry
    ChatModel = apps.get_model('ai', 'ChatModel')
    Chat = apps.get_model('ai', 'Chat')
    

    # Iterate through all instances of ChatModel
    for chat_model in ChatModel.objects.all():
        # Replace this with your custom logic to calculate usage count
        # Here is an example where you can define your factors
        # For instance, we could just increment it based on the level
        usage = Chat.objects.filter(model_name=chat_model.name).count()
        chat_model.usage_count = usage  # Example logic
        chat_model.save(update_fields=['usage_count'])

class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_chatmodel_level_chatmodel_output_token_and_more'),
    ]

    operations = [
        migrations.RunPython(update_usage_count), 
    ]
