# Generated by Django 5.2.5 on 2025-08-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_auto_20250816_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmodel',
            options={'ordering': ('usage_count', 'level', 'name')},
        ),
    ]
