# Generated by Django 5.2.5 on 2025-08-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_alter_chatmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='input_token',
            field=models.FloatField(default=0.0),
        ),
    ]
