# Generated by Django 5.2.5 on 2025-08-22 09:05

from django.db import migrations, models
from django.contrib.auth import get_user_model
from django.conf import settings

User = get_user_model()

def set_default_user(apps, schema_editor):
    Chat = apps.get_model('ai', 'Chat')
    default_user = User.objects.get(id=1)  # Assuming user with id=1 exists
    Chat.objects.all().update(user=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_chatmodel_input_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,                
                on_delete=models.CASCADE,
                related_name='chats',
                default=1,  # Temporarily set a default
            ),
        ),
        migrations.RunPython(set_default_user),
        
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,                
                on_delete=models.CASCADE,
                related_name='chats',
            ),
        ),
    ]
