# Generated by Django 5.2.5 on 2025-09-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_auto_20250822_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='model_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('image', 'Image generator')], default='chat', max_length=10, verbose_name='Model type'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_type',
            field=models.CharField(choices=[('', 'Not Applied'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('doc', 'Document'), ('pdf', 'PDF')], default='', max_length=12),
        ),
    ]
