# Generated by Django 5.2.5 on 2025-09-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_chatmodel_model_type_alter_message_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='error',
            field=models.TextField(blank=True),
        ),
    ]
