# Generated by Django 6.0 on 2025-12-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_message_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created',)},
        ),
    ]
