# Generated by Django 4.1.7 on 2023-04-05 12:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Account title')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Card number')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account number')),
                ('BIN', models.CharField(blank=True, max_length=24, null=True, verbose_name='BIN')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('initial_level', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Bank account',
                'verbose_name_plural': 'Bank accounts',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='TransactionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('transaction_kind', models.CharField(choices=[('pay', 'Payment'), ('rec', 'Receive')], default='pay', max_length=3)),
            ],
            options={
                'verbose_name': 'Transaction subject',
                'verbose_name_plural': 'Transaction subjects',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount_pay', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Pay amount')),
                ('amount_rec', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Receive amount')),
                ('account_level', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Account level')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Transaction date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='accounting/receipt', verbose_name='Receipt image')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='accounting/receipt', verbose_name='Receipt file')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.bankaccount')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.transactionsubject')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ('-pk',),
            },
        ),
    ]
