# Generated by Django 4.1.7 on 2023-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_transaction_registrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='current_level',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
